create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  category text not null default 'Accesorios',
  price_cents integer not null check (price_cents > 0),
  inventory integer not null default 0 check (inventory >= 0),
  active boolean not null default true,
  featured boolean not null default false,
  image_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  delivery_method text not null check (delivery_method in ('shipping', 'pickup')),
  address text,
  payment_method text not null check (payment_method in ('card', 'paypal', 'ath')),
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid', 'refunded', 'cancelled')),
  fulfillment_status text not null default 'new' check (fulfillment_status in ('new', 'making', 'ready', 'shipped', 'complete', 'cancelled')),
  subtotal_cents integer not null default 0,
  shipping_cents integer not null default 0,
  tax_cents integer not null default 0,
  total_cents integer not null default 0,
  processor_reference text,
  notes text,
  inventory_reserved boolean not null default true,
  confirmation_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price_cents integer not null check (unit_price_cents > 0)
);

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete set null,
  email text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists admins_email_lower_unique on public.admins (lower(email));
create index if not exists products_storefront_idx on public.products (active, featured desc, created_at desc);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_processor_reference_idx on public.orders (processor_reference);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.admins enable row level security;

-- The browser never reads these tables directly. Vercel API routes use the
-- service-role key after validating the request and the admin allowlist.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  false,
  8000000,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.create_store_order(
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_delivery_method text,
  p_address text,
  p_payment_method text,
  p_notes text,
  p_items jsonb,
  p_shipping_cents integer default 0,
  p_tax_rate numeric default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid := gen_random_uuid();
  v_order_number text := 'MED-' || to_char(now() at time zone 'utc', 'YYYY') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_subtotal integer := 0;
  v_shipping integer := greatest(coalesce(p_shipping_cents, 0), 0);
  v_tax integer;
  v_total integer;
  v_items jsonb;
begin
  if nullif(trim(p_customer_name), '') is null or position('@' in p_customer_email) < 2 or nullif(trim(p_customer_phone), '') is null then
    raise exception 'Completa tu información de contacto.';
  end if;
  if p_delivery_method not in ('shipping', 'pickup') or p_payment_method not in ('card', 'paypal', 'ath') then
    raise exception 'La entrega o el método de pago no es válido.';
  end if;
  if p_tax_rate < 0 or p_tax_rate > 1 then
    raise exception 'La tasa de impuesto configurada no es válida.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El carrito está vacío.';
  end if;
  if p_delivery_method = 'pickup' then
    v_shipping := 0;
  end if;

  insert into public.orders (
    id, order_number, customer_name, customer_email, customer_phone,
    delivery_method, address, payment_method, notes
  ) values (
    v_order_id, v_order_number, trim(p_customer_name), lower(trim(p_customer_email)), trim(p_customer_phone),
    p_delivery_method, nullif(trim(p_address), ''), p_payment_method, nullif(trim(p_notes), '')
  );

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(coalesce((v_item->>'quantity')::integer, 0), 0);
    if v_quantity < 1 or v_quantity > 20 then
      raise exception 'Una cantidad del carrito no es válida.';
    end if;

    select * into v_product
    from public.products
    where id = (v_item->>'product_id')::bigint and active = true
    for update;

    if not found then
      raise exception 'Una de las piezas ya no está disponible.';
    end if;
    if v_product.inventory < v_quantity then
      raise exception 'No queda suficiente inventario de %.', v_product.name;
    end if;

    update public.products
    set inventory = inventory - v_quantity, updated_at = now()
    where id = v_product.id;

    insert into public.order_items (order_id, product_id, product_name, quantity, unit_price_cents)
    values (v_order_id, v_product.id, v_product.name, v_quantity, v_product.price_cents);

    v_subtotal := v_subtotal + (v_product.price_cents * v_quantity);
  end loop;

  v_tax := round(v_subtotal * p_tax_rate)::integer;
  v_total := v_subtotal + v_shipping + v_tax;

  update public.orders
  set subtotal_cents = v_subtotal,
      shipping_cents = v_shipping,
      tax_cents = v_tax,
      total_cents = v_total,
      updated_at = now()
  where id = v_order_id;

  select jsonb_agg(jsonb_build_object(
    'product_id', product_id,
    'name', product_name,
    'quantity', quantity,
    'unit_price_cents', unit_price_cents
  ) order by id)
  into v_items
  from public.order_items
  where order_id = v_order_id;

  return jsonb_build_object(
    'id', v_order_id,
    'order_number', v_order_number,
    'subtotal_cents', v_subtotal,
    'shipping_cents', v_shipping,
    'tax_cents', v_tax,
    'total_cents', v_total,
    'items', coalesce(v_items, '[]'::jsonb)
  );
end;
$$;

create or replace function public.cancel_store_order(p_order_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_item record;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found or v_order.payment_status <> 'pending' then
    return false;
  end if;

  if v_order.inventory_reserved then
    for v_item in select product_id, quantity from public.order_items where order_id = p_order_id
    loop
      update public.products
      set inventory = inventory + v_item.quantity, updated_at = now()
      where id = v_item.product_id;
    end loop;
  end if;

  update public.orders
  set payment_status = 'cancelled', fulfillment_status = 'cancelled', inventory_reserved = false, updated_at = now()
  where id = p_order_id;
  return true;
end;
$$;

create or replace function public.mark_store_order_paid(p_order_id uuid, p_processor_reference text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
begin
  select payment_status into v_status from public.orders where id = p_order_id for update;
  if not found or v_status = 'cancelled' then
    return false;
  end if;
  update public.orders
  set payment_status = 'paid',
      inventory_reserved = false,
      processor_reference = coalesce(p_processor_reference, processor_reference),
      updated_at = now()
  where id = p_order_id;
  return true;
end;
$$;

revoke all on function public.create_store_order(text, text, text, text, text, text, text, jsonb, integer, numeric) from public;
revoke all on function public.cancel_store_order(uuid) from public;
revoke all on function public.mark_store_order_paid(uuid, text) from public;
grant execute on function public.create_store_order(text, text, text, text, text, text, text, jsonb, integer, numeric) to service_role;
grant execute on function public.cancel_store_order(uuid) to service_role;
grant execute on function public.mark_store_order_paid(uuid, text) to service_role;
